site_name: Blogging 蟒营™ 博客
copyright: 2019 蟒营™101camp

theme:
    name: null
    custom_dir: mkdocs_alabaster

nav:
  - Home: index.md
  - License: license.md
  - theme: alabaster/index.md
#  - DM: DM/_index.md
#  - NC: NC/_index.md
#  - SS: SS/_index.md
#  - TS: TS/_index.md

markdown_extensions:
  - toc:
      permalink: "¶"

extra:
  logo: logo.png
  include_toc: yes
  extra_nav_links:
    edit on GitHub: https://github.com/101camp/blog
