site_name: Blogging蟒营™
copyright: 2019 蟒营™101camp

theme:
    name: null
    custom_dir: mkdocs_alabaster

nav:
  - Home: index.md
  - User Guide: guide.md
  - Developer Guide: dev.md
  - License: license.md

markdown_extensions:
  - toc:
      permalink: "¶"

extra:
  logo: logo.png
  include_toc: yes
  extra_nav_links:
    edit on GitHub: https://github.com/101camp/blog
